<?php
namespace Home\Controller;
use Think\Controller;
use Home\Controller\BaseController;
use Think\Drink;

class DrinkController extends BaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $ma_id = $_SESSION['ma_id'];
        //判断商家是否正常
        $mart['delete'] = 1;
        $mart['is_open'] = 1;
        $mart['due_deadline'] = array('GT',time());
        $mart['ma_id'] = $ma_id;
        $ret = M("merchant")->field("ma_id")->where($mart)->find();
        if (empty($ret)){
            redirect(U('Index/errors'));
        }
    }

    //点餐首页
    public function index()
    {
        /*$orders_db = M('orders');
        foreach ($stall as $key=>$value){
            //时间
            $time = time();
            $starttime = strtotime(date('Y-m-d',strtotime(date("Y-m",strtotime("last month"))))." 00:00:00");
            $endtime = strtotime(date('Y-m-d',strtotime(date("Y-m",$time)))." 00:00:00");
            $where1['b.stall_id'] = $value['stall_id'];
            $where1['b.order_status'] = array('in','5,6');
            $where1['b.create_time'] = array('egt',$starttime);
            $where1['b.create_time'] = array('elt',$endtime);
            $goodsList = $orders_db->alias('b')
                ->join("LEFT JOIN __ORDER_GOODS__ as c on b.order_id = c.order_id")
                ->where($where1)
                ->sum('dishes_nums');
            if(!empty($goodsList)){
                $stall[$key]['sales'] = $goodsList;
            }else{
                $stall[$key]['sales'] = 0;
            }
        }*/
        $ma_id = $_SESSION['ma_id'];
        //判断是不是配送员
        $status = M('member_list')->where(array('member_list_id'=>session('member_list_id'),'is_del'=>2))->getField('status');
        //轮播图
        $banner_list = M('merchant_banner')->where(array('ma_id'=>$ma_id))->select();
        //饱和度
        //$status = M('merchant')->where(array('ma_id'=>$ma_id))->getField('saturation');
        //推荐
        $recom = M('dishes')->alias('a')
            ->field("a.dishes_id,a.pic_url,a.dishes_name,a.type")
            ->join("LEFT JOIN __STALL__ as b on a.stall = b.stall_id")
            ->where(array('a.is_del'=>2,'a.ma_id'=>$ma_id,'a.state'=>1,'a.statue'=>2,'a.num'=>array('GT',0),'b.delete'=>2,'b.is_freeze'=>2))
            ->limit(6)
            ->order("a.sort ASC,a.addtime DESC")
            ->select();
        //档口
        $stall = M('stall')
            //->field("stall_id,image,stall_name,score,addtime,on_the_pin,stall_type")
            ->where(array('delete'=>2,'is_freeze'=>2,'ma_id'=>$ma_id))
            //->limit(20)
            ->order("sort asc")
            ->count();
        //获取用户位置
        $shopData = M('merchant')->field("appid,appsecret,saturation")->where("ma_id='$ma_id'")->find();
        $appid = $shopData['appid'];
        $appsecret = $shopData['appsecret'];
        Vendor('Wxshare.jssdk');
        $token = get_access_token($appid,$appsecret);
        $jssdk = new \JSSDK($appid,$appsecret,$token);
        // var_dump($token);
        $signPackage = $jssdk->getSignPackage();

        $this->assign('status',$status);
        $this->assign('banner_list',$banner_list);
        $this->assign('shopData',$shopData);
        $this->assign('recom',$recom);
        $this->assign('stall',$stall);
        $this->assign('signPackage', $signPackage);
        $this->display();
    }

    //距离
    public function distance()
    {
        $ma_id = $_SESSION['ma_id'];
        $post = I('post.');
        //纬度小，经度大
        $longitude = $post['longitude'];//经度信息
        $latitude = $post['latitude'];//纬度信息
        session('longitude',$longitude);
        session('latitude',$latitude);
        $merchant = M('merchant')->field("longitude,latitude")->where(array('ma_id'=>$ma_id))->find();
        $distance = $this->getDistanceByGaoDe($longitude,$latitude,$merchant['longitude'],$merchant['latitude']);
        //$distance = $this->getDistanceByGaoDe(114.646454,37.950695,114.646454,37.958695);
        $shuchu = '距餐厅'.$distance;
        $this->ajaxReturn($shuchu);
    }
    public function getDistanceByGaoDe($slng, $slat, $elng, $elat,$decimal=1)
    {
        $earth_radius = 6378.137;//地球半径
        $lng1 = (M_PI / 180) * $slng;
        $lng2 = (M_PI / 180) * $elng;
        $lat1 = (M_PI / 180) * $slat;
        $lat2 = (M_PI / 180) * $elat;
        // 两点间距离 km，如果想要米的话，结果*1000就可以了
        $d = acos(
                sin($lat1) * sin($lat2)
                + cos($lat1) * cos($lat2) * cos($lng2 - $lng1)
            ) * $earth_radius;
        // 精度2位小数
        if ($d < 1){
            $d = round($d*1000,0).'m';
        }else{
            $d = round($d,$decimal).'km';
        }

        return $d;
    }

    //搜索
    public function search()
    {
        $ma_id = $_SESSION['ma_id'];
        $where = array();
        $search = trim(I('search'));
        if(!empty($search)){
            $dishes = M('dishes');
            $where['a.is_del'] = 2;
            $where['a.ma_id'] = $ma_id;
            $where['a.state'] = 1;
            $where['b.delete'] = 2;
            $where['b.is_freeze'] = 2;
            $where['a.dishes_name'] = array('like','%'.$search.'%');//搜索
            //折扣
            $discounts = I('discount');
            $disc = M('discount')->where(array('ma_id'=>$ma_id,'start_time'=>array('ELT',date('Hi',time())),'end_time'=>array('GT',date('Hi',time()))))->field('discount,start_time,end_time')->find();

            if(empty($disc['discount'])){
                $disc['discount'] = 10;
                if(!empty($discounts)){
                    $where['a.statue'] = 6;
                    $kong = 1;
                }
            }else{
                if(!empty($discounts)){
                    $where['a.statue'] = 3;
                }
            }
            //排序
            $sort = I('sort');
            switch ($sort) {
                case 5:
                    $order = 'a.on_the_pin DESC,a.dishes_id DESC';
                    break;
                case 4:
                    $order = 'a.score DESC,a.dishes_id DESC';
                    break;
                case 3:
                    $order = 'a.price ASC,a.dishes_id DESC';
                    break;
                case 2:
                    $order = 'a.price DESC,a.dishes_id DESC';
                    break;
                default:
                    $order = 'a.sort ASC,a.addtime DESC,a.dishes_id DESC';
                    break;
            }

            $list = $dishes->alias('a')
                ->field("a.dishes_id,a.type,a.pic_url,a.dishes_name,a.discount,a.statue,a.score,a.hot,a.price,a.on_the_pin,b.stall_name")
                ->join("LEFT JOIN __STALL__ as b on a.stall = b.stall_id")
                ->where($where)
                ->order($order)
                ->select();
            foreach ($list as $key=>$value){
                //精选菜品
                if($value['statue'] == 2 && $value['discount']!=10){
                    $list[$key]['kill_price'] = sprintf("%.2f",$value['price']*$value['discount']/10);
                }elseif($value['statue'] == 3){
                    $list[$key]['start_time'] = substr_replace($disc['start_time'], ':', -2, 0);
                    $list[$key]['end_time'] = substr_replace($disc['end_time'], ':', -2, 0);
                    if (!empty($disc['discount'])) {
                        $list[$key]['kill_price'] = sprintf("%.2f",$value['price']*$disc['discount']/10);
                        
                    }
                }
            }
        }else{
            $list = '';
        }

        $this->assign('sort',$sort);
        $this->assign('discounts',$discounts);
        $this->assign('search',$search);
        $this->assign('list',$list);
        $this->assign('disc',$disc);
        $this->assign('kong',$kong);
        $this->display();
    }

    //推荐
    public function recommend()
    {
        $ma_id = $_SESSION['ma_id'];
        //排序
        $sort = I('sort');
        switch ($sort) {
            case 5:
                $order = 'a.on_the_pin DESC,a.dishes_id DESC';
                break;
            case 4:
                $order = 'a.score DESC,a.dishes_id DESC';
                break;
            case 3:
                $order = 'a.price ASC,a.dishes_id DESC';
                break;
            case 2:
                $order = 'a.price DESC,a.dishes_id DESC';
                break;
            default:
                $order = 'a.sort ASC,a.addtime DESC,a.dishes_id DESC';
                break;
        }
        $list = M('dishes')->alias('a')
            ->field("a.dishes_id,a.type,a.pic_url,a.dishes_name,a.score,a.hot,a.discount,a.price,a.on_the_pin,b.stall_name")
            ->join("LEFT JOIN __STALL__ as b on a.stall = b.stall_id")
            ->where(array('a.is_del'=>2,'a.ma_id'=>$ma_id,'a.state'=>1,'a.statue'=>2,'a.num'=>array('GT',0),'b.delete'=>2,'b.is_freeze'=>2))
            ->order($order)
            ->select();
        /*$orders_db = M('orders');
        foreach ($list as $key=>$value){
            //时间
            $time = time();
            $starttime = strtotime(date('Y-m-d',strtotime(date("Y-m",strtotime("last month"))))." 00:00:00");
            $endtime = strtotime(date('Y-m-d',strtotime(date("Y-m",$time)))." 00:00:00");
            if($value['type'] == 1){
                $where1['b.order_type'] = 1;
                $where1['b.order_status'] = array('in','5,6');
                $where1['b.create_time'] = array('egt',$starttime);
                $where1['b.create_time'] = array('elt',$endtime);
                $where1['c.dishes_id'] = $value['dishes_id'];
                $goodsList = $orders_db->alias('b')
                    ->join("LEFT JOIN __ORDER_GOODS__ as c on b.order_id = c.order_id")
                    ->where($where1)
                    ->sum('dishes_nums');
            }else{
                $where2['order_type'] = 2;
                $where2['order_status'] = array('in','5,6');
                $where2['create_time'] = array('egt',$starttime);
                $where2['create_time'] = array('elt',$endtime);
                $where2['dishes_id'] = $value['dishes_id'];
                $goodsList = $orders_db->where($where2)->count();
            }

            if(!empty($goodsList)){
                $list[$key]['sales'] = $goodsList;
            }else{
                $list[$key]['sales'] = 0;
            }
        }
        //销量
        $sales = I('sales');
        if(!empty($sales)){
            $sort = array_column($list, 'sales');
            $dishes_id = array_column($list, 'dishes_id');
            array_multisort($sort,SORT_DESC,$dishes_id,SORT_DESC,$list);
        }*/
        // dump($list);
        $this->assign('sort',$sort);
        $this->assign('list',$list);
        $this->display();
    }

    //测试
    public function indexb()
    {
        $ma_id = $_SESSION['ma_id'];
        //判断是不是配送员
        $status = M('member_list')->where(array('member_list_id'=>session('member_list_id'),'is_del'=>2))->getField('status');
        //轮播图
        $banner_list = M('merchant_banner')->where(array('ma_id'=>$ma_id))->select();
        //饱和度
        //$status = M('merchant')->where(array('ma_id'=>$ma_id))->getField('saturation');
        //推荐
        $recom = M('dishes')->alias('a')
            ->field("a.dishes_id,a.pic_url,a.dishes_name,a.type")
            ->join("LEFT JOIN __STALL__ as b on a.stall = b.stall_id")
            ->where(array('a.is_del'=>2,'a.ma_id'=>$ma_id,'a.state'=>1,'a.statue'=>2,'a.num'=>array('GT',0),'b.delete'=>2,'b.is_freeze'=>2))
            ->limit(6)
            ->order("a.sort ASC,a.addtime DESC")
            ->select();
        //获取用户位置
        $shopData = M('merchant')->field("appid,appsecret,saturation")->where("ma_id='$ma_id'")->find();
        $appid = $shopData['appid'];
        $appsecret = $shopData['appsecret'];
        Vendor('Wxshare.jssdk');
        $token = get_access_token($appid,$appsecret);
        $jssdk = new \JSSDK($appid,$appsecret,$token);
        $signPackage = $jssdk->getSignPackage();

        $this->assign('status',$status);
        $this->assign('banner_list',$banner_list);
        $this->assign('shopData',$shopData);
        $this->assign('recom',$recom);
        $this->assign('signPackage', $signPackage);
        $this->display();
    }
    //分页
    public function indexLists()
    {
        $psize = I('psize',20); //每页显示条数
        $page = I('page',1);  //当前页
        $offset = ($page - 1) * $psize;

        $ma_id = $_SESSION['ma_id'];
        $where = array();
        $where['delete'] = 2;
        $where['is_freeze'] = 2;
        $where['ma_id'] = $ma_id;

        $list = M('stall')->alias('a')
            ->field("stall_id,image,stall_name,score,addtime,on_the_pin,stall_type")
            ->where($where)
            ->limit($offset,$psize)
            ->order("sort asc,on_the_pin DESC,addtime DESC")
            ->select();
        //$str .= '<a href="/index.php/Home/Stall/stallDetail?stall_id='.$v[stall_id].'">'
        if ($list) {
            $str = '';
            foreach ($list as $v) {
                $str .= '<li class="stallDetail" data-id="' . $v[stall_id] . '" data-type="' . $v[stall_type] . '">'
                    . '<div class="img" style="background:url(' . $v[image] . ') no-repeat center;background-size:cover;width:122px;height:122px;" ></div>'
                    . '<div class="cantingDiv">'
                    . '<p class="name" style="color: #0C0C0C">' . $v[stall_name] . '</p>'
                    . '<p class="starDiv">';
                for ($x=0; $x< $v['score']; $x++) {
                    $str .= '<img src="home/images/star_icon24.png" alt="" />';
                }
                for ($y=0; $y< 5-$v[score]; $y++) {
                    $str .= '<img src="home/images/star_icon25.png" alt="" />';
                }
                $str .='<span>'.sprintf('%.1f',$v[score]).'</span>'
                    .'</p>'
                    .'<p class="darkGreyColor">月销<span>'.$v[on_the_pin].'</span></p>'
                    .'</div>'
                    .'</li>';
            }
            echo $str;
        }else{
            echo 1;
        }
    }




}