<?php
// +----------------------------------------------------------------------
// |  周餐档口
// +----------------------------------------------------------------------
namespace Home\Controller;
class PackageController extends BaseController
{
    /*public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $ma_id = $_SESSION['ma_id'];
        //判断商家是否正常
        $mart['ma_id'] = $ma_id;
        $mart['delete'] = 1;
        $mart['is_open'] = 1;
        $mart['due_deadline'] = array('GT',time());
        $mart['due_deadline'] = array('GT',time());
        $mart['start_time'] =  array('ELT',time());
        $mart['end_time'] =  array('EGT',time());
        $ret = M("merchant")->field("ma_id")->where($mart)->find();
        if (empty($ret)){
            redirect(U('Home/Index/errors'));
        }
    }*/

    //周餐档口（菜品）
    public function index()
    {
        $member_list_id = session('member_list_id');
        $stall_id = I('stall_id');

        $stallDb = M('stall');
        $dishesDb = M('dishes');
        $stallData = $stallDb->where(array('stall_id'=>$stall_id))->find();
        $stallData['score'] = sprintf("%.1f",$stallData['score']);
        // 推荐菜品
        $tuijian = $dishesDb->where(array('stall'=>$stall_id,'statue'=>2,'state'=>1))->limit(6)->order("sort ASC,addtime desc")->field("dishes_id,ma_id,num,dishes_name,pic_url")->select();
        // dump($tuijian);
        $ma_id = $dishesDb->where(array('stall'=>$stall_id))->getField("ma_id");
        $type = M('dishes_category')->where(array('ma_id'=>$ma_id,'is_del'=>2))->order('sort DESC')->select();
        $stallType = $dishesDb->where(array('ma_id'=>$ma_id,'stall'=>$stall_id))->group('dishes_cate_id')->order("sort ASC")->field('dishes_cate_id')->select();
        $s = array();
        $i = 0;
        foreach ($type as $key => $value) {
            foreach ($stallType as $k => $v) {
                if ($value['dishes_cate_id'] == $v['dishes_cate_id']) {
                    $s[$i]['dishes_cate_id'] = $value['dishes_cate_id'];
                    $s[$i]['cat_name'] = $value['cat_name'];
                    $s[$i]['sort'] = $value['sort'];
                    $i++;
                    unset($stallType[$k]);
                }
            }
        }

        $where['a.stall_id'] = $stall_id;
        //$where['a.is_del'] = 2;
        $evaluationData = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")
            ->join("LEFT JOIN sm_member_list as c on a.member_list_id = c.member_list_id")->where($where)->limit(5)->order('a.addtime DESC')
            ->field('a.member_list_id,a.is_del,c.member_list_headpic,c.member_list_nickname,a.dish_score,a.service_score,a.addtime,a.image,a.content,a.order_id,b.dishes_name')
            ->select();
        foreach ($evaluationData as $k => $v){
            //$score = $v['dish_score']+$v['service_score'];

            $score = $v['dish_score'];
            $evaluationData[$k]['addtime'] = date("Y-m-d H:i",$v['addtime']);
            $evaluationData[$k]['score'] = ceil($score);
            $evaluationData[$k]['endscore'] = 5-ceil($score);
            $evaluationData[$k]['images'] = explode(',',$v['image']);
            if($v['member_list_id'] != session('member_list_id') && $v['is_del'] == 1){
                unset($evaluationData[$k]);
            }
        }

        // 是否需收藏
        $is_sc = M('member_collection')->where(array('member_list_id'=>$member_list_id,'stall_id'=>$stall_id))->find();
        if(empty($is_sc)){
            $stallData['is_sc'] = 2;
        }else{
            $stallData['is_sc'] = 1;
        }

        $end = 5-$stallData['score'];
        $this->assign('end',$end);
        $this->assign('typeCategory',$s);
        $this->assign('tuijian',$tuijian);
        $this->assign('stallData',$stallData);
        $this->assign('evaluationData',array_values($evaluationData));

        $this->display();
    }

    //档口评价
    public function stallevaluation()
    {
        $stall_id = I('stall_id');
        //总条数
        $num = 5;
        $count = M('comment')->where(array('stall_id'=>$stall_id,'is_del'=>2))->count();
        $totalPage = ceil($count/$num);//总计页数
        $evaluationData['totalPage'] = $totalPage;

        $where['a.stall_id'] = $stall_id;
        //$where['a.is_del'] = 2;
        $evaluationData['list'] = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")
            ->join("LEFT JOIN sm_member_list as c on a.member_list_id = c.member_list_id")->where($where)->limit($num)->order('a.addtime DESC')
            ->field('a.member_list_id,a.is_del,c.member_list_headpic,c.member_list_nickname,a.dish_score,a.service_score,a.addtime,a.image,a.content,a.order_id,b.dishes_name')
            ->select();
        foreach ($evaluationData['list'] as $k => $v){
            $score = $v['dish_score']+$v['service_score'];
            //$score = $v['dish_score'];
            $evaluationData['list'][$k]['addtime'] = date("Y-m-d H:i",$v['addtime']);
            $evaluationData['list'][$k]['score'] = ceil($score/2);
            $evaluationData['list'][$k]['endscore'] = 5-ceil($score/2);
            if($v['image'] == ''){
                $evaluationData['list'][$k]['images'] = '';
            }else{
                $evaluationData['list'][$k]['images'] = explode(',',$v['image']);
            }
            if($v['member_list_id'] != session('member_list_id') && $v['is_del'] == 1){
                unset($evaluationData['list'][$k]);
            }
        }
        $this->make_json_result(1,$evaluationData);
    }

    //更多评价
    public function evaluationList()
    {
        $p = I('k',0,'intval');
        $num = 5;//每页记录数
        $limitpage = ($p)*$num;//每次查
        $stall_id = I('stall_id');
        $where['a.stall_id'] = $stall_id;
        //$where['a.is_del'] = 2;
        $evaluationData['list'] = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")
            ->join("LEFT JOIN sm_member_list as c on a.member_list_id = c.member_list_id")
            ->where($where)
            ->limit($limitpage,$num)
            ->order('a.addtime DESC')
            ->field('a.member_list_id,a.is_del,c.member_list_headpic,c.member_list_nickname,a.dish_score,a.service_score,a.addtime,a.image,a.content,a.order_id,b.dishes_name')
            ->select();
        foreach ($evaluationData['list'] as $k => $v){
            $score = $v['dish_score']+$v['service_score'];
            //$score = $v['dish_score'];
            $evaluationData['list'][$k]['addtime'] = date("Y-m-d H:i",$v['addtime']);
            $evaluationData['list'][$k]['score'] = ceil($score/2);
            $evaluationData['list'][$k]['endscore'] = 5-ceil($score/2);
            if($v['image'] == ''){
                $evaluationData['list'][$k]['images'] = '';
            }else{
                $evaluationData['list'][$k]['images'] = explode(',',$v['image']);
            }
            if($v['member_list_id'] != session('member_list_id') && $v['is_del'] == 1){
                unset($evaluationData[$k]);
            }
        }
        $this->make_json_result(1,$evaluationData);
    }

    // 收藏
    public function collection(){
        $member_list_id = session('member_list_id');
        $stall_id = I('stall_id');
        $member_collection_db = M('member_collection');
        $res = $member_collection_db->where(array('member_list_id'=>$member_list_id,'stall_id'=>$stall_id))->getField('collection_id');
        if(empty($res)){
            $data['member_list_id'] = $member_list_id;
            $data['stall_id'] = $stall_id;
            $data['addtime'] = time();
            $member_collection_db->add($data);
            $this->ajaxReturn(1);
        }else{
            $member_collection_db->where(array('collection_id'=>$res))->delete();
            $this->ajaxReturn(2);
        }
    }

    //周餐档口（菜品详情）
    public function dishesDetails()
    {
        $dishes_id = I('dishes_id');
        $list = M('dishes')->where(array('dishes_id'=>$dishes_id))->find();
        $list['score'] = sprintf("%.1f",$list['score']);
        if($list['statue'] == 3){
            $discount = M('discount')->where(array('ma_id'=>$list['ma_id'],'start_time'=>array('elt',date("Hi")),'end_time'=>array('egt',date("Hi"))))->field('discount,start_time,end_time')->find();
            if(!empty($discount)){
                $list['discount'] = sprintf("%.1f",$discount['discount']);
                $list['realMoney'] = sprintf("%.2f",$list['price']*$discount['discount']/10);
                $list['start_time'] = substr_replace($discount['start_time'], ':', -2, 0);
                $list['end_time'] = substr_replace($discount['end_time'], ':', -2, 0);
            }
        }
        if($list['statue'] == 2){
            $list['discount'] = sprintf("%.1f",$list['discount']);
            $list['realMoney'] = sprintf("%.2f",$list['price']*$list['discount']/10);
        }

        $where['b.dishes_id'] = $dishes_id;
        //$where['a.is_del'] = 2;
        $evaluationData = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")
            ->join("LEFT JOIN sm_member_list as c on a.member_list_id = c.member_list_id")->where($where)->limit(3)->order('a.addtime DESC')
            ->field('a.member_list_id,a.is_del,c.member_list_headpic,c.member_list_nickname,a.dish_score,a.service_score,a.addtime,a.image,a.content,a.order_id,b.dishes_name')
            ->select();
        $evaluationDataCount = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")->where($where)->count();
        foreach ($evaluationData as $k => $v){
            //$score = $v['dish_score']+$v['service_score'];
            $score = $v['dish_score'];
            $evaluationData[$k]['addtime'] = date("Y-m-d H:i",$v['addtime']);
            $evaluationData[$k]['score'] = ceil($score);
            $evaluationData[$k]['endscore'] = 5-ceil($score);
            if($v['image'] == ''){
                $evaluationData[$k]['images'] = '';
            }else{
                $evaluationData[$k]['images'] = explode(',',$v['image']);
            }
            if($v['member_list_id'] != session('member_list_id') && $v['is_del'] == 1){
                unset($evaluationData[$k]);
            }
        }
        $this->assign('evaluationData',$evaluationData);
        $this->assign('evaluationDataCount',$evaluationDataCount);
        $this->assign('list',$list);
        $this->display();
    }

    //周餐餐品
    public function NextGoods()
    {
        $dishes_id = I('dishes_id');
        $ma_id = I('ma_id');
        $type = I('type');
        $day = I('day');
        $dishesIds = M('dishes_meal')->where(array('dishes_id'=>$dishes_id,'ma_id'=>$ma_id,'type'=>$type,'day'=>$day))->getField("dishes_ids");
        if($dishesIds){
            $dishesData = M('dishes')->where(array('dishes_id'=>array('in',$dishesIds)))->field("dishes_id,dishes_name,pic_url,num,price,hot")->select();
            $this->ajaxReturn($dishesData);
        }else{
            $this->ajaxReturn(404);
        }
    }

    //查找分类下的商品
    public function searchGoods()
    {
        $dishes_cate_id = I('dishes_cate_id');
        $ma_id = I('ma_id');
        $stall_id = I('stall_id');
        $goodsData = M('dishes')->where(array('stall'=>$stall_id,'dishes_cate_id'=>$dishes_cate_id,'ma_id'=>$ma_id,'is_del'=>2,'state'=>1))
            ->field("dishes_id,ma_id,dishes_name,hot,price,score,on_the_pin,pic_url,statue,discount,num")
            ->order('sort asc')
            ->select();
        foreach ($goodsData as $key =>$value){
            $goodsData[$key]['score'] = sprintf("%.1f",$value['score']);
            if($value['statue'] == 3){
                $discount = M('discount')->where(array('ma_id'=>$value['ma_id'],'start_time'=>array('elt',date("Hi")),'end_time'=>array('egt',date("Hi"))))->field('discount,start_time,end_time')->find();
                if(!empty($discount)){
                    $goodsData[$key]['discount'] = sprintf("%.1f",$discount['discount']);
                    $goodsData[$key]['realMoney'] = sprintf("%.2f",$value['price']*$discount['discount']/10);
                    $goodsData[$key]['start_time'] = substr_replace($discount['start_time'], ':', -2, 0);
                    $goodsData[$key]['end_time'] = substr_replace($discount['end_time'], ':', -2, 0);
                }
            }
            if($value['statue'] == 2){
                $goodsData[$key]['discount'] = sprintf("%.1f",$value['discount']);
                $goodsData[$key]['realMoney'] = sprintf("%.2f",$value['price']*$value['discount']/10);
            }
        }
        $this->ajaxReturn($goodsData);
    }

    //结算页面
    public function settlement()
    {
        $dishes_id = I('dishes_id');
        $list = M('dishes')->join("AS a LEFT JOIN __STALL__ as b on a.stall = b.stall_id")->join("LEFT JOIN __MERCHANT__ as c on a.ma_id = c.ma_id")
            ->where(array('a.dishes_id'=>$dishes_id))
            ->field("a.dishes_id,a.ma_id,a.dishes_name,a.pic_url,a.num,a.price,a.statue,b.stall_name,b.stall_tel,c.address,a.discount")
            ->find();
        $score = M('sysconfig')->where(array('aid'=>47))->getField("value");
        if($list['statue'] == 3){
            $discount = M('discount')->where(array('ma_id'=>$list['ma_id'],'start_time'=>array('elt',date("Hi")),'end_time'=>array('egt',date("Hi"))))->getField('discount');
            if(!empty($discount)){
                $list['discount'] = sprintf("%.1f",$discount);
                $list['realMoney'] = sprintf("%.2f",$list['price']*$discount/10);
                $list['score'] = floor($list['realMoney']*$score);
            }else{
                $list['score'] = floor($list['price']*$score);
            }
        }elseif($list['statue'] == 2){
            if($list['discount']<10){
                $list['discount'] = sprintf("%.1f",$list['discount']);
                $list['realMoney'] = sprintf("%.2f",$list['price']*$list['discount']/10);
                $list['score'] = floor($list['realMoney']*$score);
            }else{
                $list['score'] = floor($list['price']*$score);
            }
        }else{
            $list['score'] = floor($list['price']*$score);
        }
        $this->assign("time",date('Y-m-d',strtotime('+1day')));
        $this->assign("list",$list);
        $this->display();
    }

    //去支付
    public function goPay()
    {

        $effect_time = I('effect_time');
        $dishes_id = I('dishes_id');
        $shopData = M('dishes')->join("AS a LEFT JOIN __MERCHANT__ as c on a.ma_id = c.ma_id")->where("a.dishes_id='$dishes_id'")->field("a.num,c.start_time,c.end_time")->find();
        $startTime = date("Y-m-d",time())." ".date("H:i",$shopData['start_time']);
        $endTime = date("Y-m-d",time())." ".date("H:i",$shopData['end_time']);

        if(strtotime($startTime)>time() || strtotime($endTime)<time()){
            $arr = array();
            $arr['memage'] = '餐厅已打烊！餐厅营业时间为：'.date("H:i",$shopData['start_time']).'～'.date("H:i",$shopData['end_time']);
            $arr['code'] = 2;
            $this->ajaxReturn($arr);
        }
        if($shopData['num'] == 0){
            $arr = array();
            $arr['memage'] = '该菜品已售罄！';
            $arr['code'] = 2;
            $this->ajaxReturn($arr);
        }
        //$dishes_id = 4;
        $memberData = M('member_list')->where(array('member_list_id'=>session('member_list_id'),'is_del'=>2))
            ->field("member_list_id,member_name,telphone,is_perfect")->find();
        if($memberData['is_perfect'] == 2){
            $arr = array();
            $arr['memage'] = '请先完善信息！';
            $arr['url'] = '/index.php?m=Home&c=Personal&a=personal_add&href=/index.php/Home/Package/settlement/dishes_id/'.$dishes_id;
            $arr['code'] = 3;
            $this->ajaxReturn($arr);
            //$href = 'Home/Package/settlement/dishes_id/'.$dishes_id;
            //$this->success('请先完善信息！',U('Home/Personal/personal_add',array('href'=>$href)),3);
        }
        $list = M('dishes')->join("AS a LEFT JOIN __STALL__ as b on a.stall = b.stall_id")->join("LEFT JOIN __MERCHANT__ as c on a.ma_id = c.ma_id")
            ->where(array('a.dishes_id'=>$dishes_id))
            ->field("a.dishes_id,a.ma_id,a.dishes_name,a.stall,a.pic_url,a.num,a.price,a.statue,b.stall_name,b.stall_tel,c.address,a.discount,c.longitude,c.latitude")
            ->find();

        $score = M('sysconfig')->where(array('aid'=>47))->getField("value");
        if($list['statue'] == 3){
            $discount = M('discount')->where(array('ma_id'=>$list['ma_id'],'start_time'=>array('elt',date("Hi")),'end_time'=>array('egt',date("Hi"))))->getField('discount');
            if(!empty($discount)){
                $list['discount'] = sprintf("%.1f",$discount);
                $list['realMoney'] = sprintf("%.2f",$list['price']*$discount/10);
                $list['score'] = floor($list['realMoney']*$score);
                $list['money'] = sprintf("%.2f",$list['price']*$discount/10);
            }else{
                $list['score'] = floor($list['price']*$score);
                $list['money'] = $list['price'];
            }
        }elseif($list['statue'] == 2){
            if($list['discount']<10){
                $list['discount'] = sprintf("%.1f",$list['discount']);
                $list['realMoney'] = sprintf("%.2f",$list['price']*$list['discount']/10);
                $list['score'] = floor($list['realMoney']*$score);
                $list['money'] = sprintf("%.2f",$list['price']*$list['discount']/10);
            }else{
                $list['score'] = floor($list['price']*$score);
                $list['money'] = $list['price'];
            }
        }else{
            $list['score'] = floor($list['price']*$score);
            $list['money'] = $list['price'];
        }
        $data['order_no'] = makeOrderNo();
        $data['member_list_id'] = session('member_list_id');
        $data['ma_id'] = $list['ma_id'];
        $data['stall_id'] = $list['stall'];
        $data['username'] = $memberData['member_name'];
        $data['phone'] = $memberData['telphone'];
        $data['address'] = $list['address'];
        $data['longitude'] = $list['longitude'];
        $data['latitude'] = $list['latitude'];
        //$data['total_money'] = $list['price'];
        $data['total_money'] = $list['money'];
        $data['discount'] = empty($list['discount'])? 10 : $list['discount'];
        $data['real_money'] = $list['money'];
        $data['integral'] = $list['score'];
        $data['create_time'] = time();
        $data['effect_time'] = strtotime($effect_time);
        $data['order_type'] = 2;
        $data['order_note'] = I('order_note');
        $data['dishes_id'] = $list['dishes_id'];
        $data['dishes_url'] = $list['pic_url'];
        $data['dishes_name'] = $list['dishes_name'];
        $data['dishes_money'] = $list['price'];
        $data['stall_address'] = $list['address'];
        $data['telphone'] = $memberData['telphone'];
        $data['stall_tel'] = $list['stall_tel'];
        $res = M('orders')->add($data);
        if($res){
            $dishes_meal = M('dishes_meal');
            $dishesDb = M('dishes');
            $day = $this->getTimeWeek(strtotime($effect_time));
            $meal_id = $dishes_meal->where(array('dishes_id'=>$dishes_id,'day'=>$day,'type'=>1))->getField("meal_id");
            if($meal_id){
                $endGoods = $dishes_meal->where(array('dishes_id'=>$dishes_id,'meal_id'=>array('egt',$meal_id)))->select();
                $startGoods = $dishes_meal->where(array('dishes_id'=>$dishes_id,'meal_id'=>array('lt',$meal_id)))->select();
                $arr = array_merge($endGoods,$startGoods);
            }else{
                $meal_id = $dishes_meal->where(array('dishes_id'=>$dishes_id,'day'=>array('egt',$day),'type'=>array('in','1,2,3')))->limit(1)->getField("meal_id");
                if($meal_id){
                    $endGoods = $dishes_meal->where(array('dishes_id'=>$dishes_id,'meal_id'=>array('egt',$meal_id)))->select();
                    $startGoods = $dishes_meal->where(array('dishes_id'=>$dishes_id,'meal_id'=>array('lt',$meal_id)))->select();
                    $arr = array_merge($endGoods,$startGoods);
                }else{
                    $meal_id = $dishes_meal->where(array('dishes_id'=>$dishes_id,'day'=>array('elt',$day),'type'=>array('in','1,2,3')))->limit(1)->getField("meal_id");
                    if($meal_id){
                        $endGoods = $dishes_meal->where(array('dishes_id'=>$dishes_id,'meal_id'=>array('egt',$meal_id)))->select();
                        $startGoods = $dishes_meal->where(array('dishes_id'=>$dishes_id,'meal_id'=>array('lt',$meal_id)))->select();
                        $arr = array_merge($endGoods,$startGoods);
                    }else{
                        $arr = array();
                        $arr['memage'] = '该周餐暂无菜品！';
                        $arr['code'] = 2;
                        $this->ajaxReturn($arr);
                    }
                }
            }
            $x = 0;
            $code = $this->getMakeCode($list['ma_id']);
            foreach ($arr as $key=>$value){
                $list = $dishesDb->where(array('dishes_id'=>array('in',explode(',',$value['dishes_ids']))))->select();
                foreach ($list as $k=>$v){
                    $order[$x]['order_id'] = $res;
                    $order[$x]['dishes_id'] = $v['dishes_id'];
                    $order[$x]['meal_id'] = $dishes_id;
                    $order[$x]['dishes_nums'] = 1;
                    $order[$x]['dishes_price'] = $v['price'];
                    $order[$x]['meal_code'] = empty($code)? $this->getMakeCode($list['ma_id']) : $code;
                    //$order[$x]['meal_code'] = $this->getMakeCode($list['ma_id']);
                    $order[$x]['addtime'] = time();
                    $order[$x]['dishes_name'] = $v['dishes_name'];
                    $order[$x]['pic_url'] = $v['pic_url'];
                    $order[$x]['type'] = $value['type'];
                    $order[$x]['day'] = $value['day'];
                    $x++;
                }
                $code = $this->getMakeCode($list['ma_id']);
            }
            $result = M('order_goods')->addAll($order);
            if($result){
                $dishesDb->where(array('dishes_id'=>$dishes_id))->setDec("num",1);
                $arr = array();
                $arr['memage'] = '下单成功！';
                $arr['url'] = '/index.php?m=Home&c=Package&a=pay&order_id='.$res;
                $arr['code'] = 1;
                $this->ajaxReturn($arr);
            }else{
                $arr = array();
                $arr['memage'] = '下单失败！';
                $arr['code'] = 2;
                $this->ajaxReturn($arr);
            }
        }else{
            $arr = array();
            $arr['memage'] = '下单失败！';
            $arr['code'] = 2;
            $this->ajaxReturn($arr);
        }
    }

    public function getTimeWeek($time, $i = 0) {
        $weekarray = array("7", "1", "2", "3", "4", "5", "6");
        $oneD = 24 * 60 * 60;
        return $weekarray[date("w", $time + $oneD * $i)];
    }

    //取餐码
    public function getMakeCode($ma_id)
    {
        $res = rand(1000,9999);
        $where['a.meal_code'] = $res;
        $where['b.ma_id'] = $ma_id;
        $where['b.order_status'] = array('lt',5);
        $where['b.order_type'] = 2;
        $pass = M('order_goods')->join("AS a left join __ORDERS__ as b on a.order_id = b.order_id")->where($where)->find();
        if($pass){
            $res = $this->getMakeCode($ma_id);
        }
        return $res;
    }

    //订单支付
    public function pay()
    {
        $ma_id = session('ma_id');
        $order_id = I('order_id');
        $orderInfo = M('orders')->where(array('order_id'=>$order_id))->find();
        $this->assign("orderInfo",$orderInfo);
        //H5 -JS微信支付
        $wechatInfo= M('merchant')->where(array('ma_id'=>$ma_id))->find();
        $appid = $wechatInfo['appid'];
        $appsecret = $wechatInfo['appsecret'];
        $GLOBALS['appid']=$appid;
        $GLOBALS['appsecret']=$appsecret;
        $GLOBALS['mchid']=$wechatInfo['partnerid'];
        $GLOBALS['keys']=$wechatInfo['keycode'];
        $GLOBALS['curl_proxy_port']=0;//8080;
        $GLOBALS['curl_proxy_host']="0.0.0.0";//"10.152.18.220";
        $GLOBALS['report_levenl']=1;
        $GLOBALS['curl_timeout']=60;
        //支付
        header("Content-type:text/html;charset=utf-8");
        Vendor("Pay.Wxpay.WxPayPubHelper");
        $JsApi_pub = new \JsApi_pub();
        //=========步骤1：网页授权获取用户openid============
        $openid = M('member_list')->where(array('member_list_id'=>session('member_list_id'),'is_del'=>2))->getField('openid');

        if($openid)
        {
            $notify_url = 'http://'.$_SERVER['HTTP_HOST'].'/package.php';
            //=========步骤2：使用统一支付接口，获取prepay_id============
            $unifiedOrder = new \UnifiedOrder_pub();
            $unifiedOrder->setParameter("openid",$openid);//微信用户
            $unifiedOrder->setParameter("body",'微信订单支付');//商品描述
            $unifiedOrder->setParameter("out_trade_no",$orderInfo['order_no']);//商户订单号
            //$money = $orderInfo['real_money'];
            $money = 0.01;
            $unifiedOrder->setParameter("total_fee",intval($money*100));//总金额
            $unifiedOrder->setParameter("notify_url",$notify_url);//通知地址
            $unifiedOrder->setParameter("trade_type","JSAPI");//交易类型
            $prepay_id = $unifiedOrder->getPrepayId();
            $JsApi_pub->setPrepayId($prepay_id['prepay_id']);
            $jsApiParameters = $JsApi_pub->getParameters();
            $this->assign('jsApiParameters',$jsApiParameters);
            //   //支付成功跳转页面
            // $success_returnUrl='http://'.$_SERVER['HTTP_HOST'].'/index.php?m=Home&c=MyCenter&a=paySuccess&order_id='.$order_id;
            // $this->assign('success_returnUrl',$success_returnUrl);
        }
        $this->display();
    }

    //餐品评价页面
    public function evaluationG(){
        $dishes_id = I('dishes_id');
        $this->assign('dishes_id',$dishes_id);
        $this->display();
    }

    // 餐品评价加载
    public function evaluationD(){
        $dishes_id = I('dishes_id');
        //总条数
        $num = 10;
        $where['b.dishes_id'] = $dishes_id;
        //$where['a.is_del'] = 2;
        $count = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")
            ->join("LEFT JOIN sm_member_list as c on a.member_list_id = c.member_list_id")->where($where)->order('a.addtime DESC')
            ->count();
        $totalPage = ceil($count/$num);//总计页数
        $data['totalPage'] = $totalPage;
        $evaluation = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")
            ->join("LEFT JOIN sm_member_list as c on a.member_list_id = c.member_list_id")->where($where)->limit($num)->order('a.addtime DESC')
            ->field('a.member_list_id,a.is_del,c.member_list_headpic,c.member_list_nickname,a.dish_score,a.service_score,a.addtime,a.image,a.content,a.order_id,b.dishes_name as names')
            ->select();
        foreach ($evaluation as $k => $v){
            //$score = $v['dish_score']+$v['service_score'];
            $score = $v['dish_score'];
            $evaluation[$k]['addtime'] = date("Y-m-d H:i",$v['addtime']);
            $evaluation[$k]['score'] = ceil($score);
            $evaluation[$k]['endscore'] = 5-ceil($score);
            $evaluation[$k]['images'] = explode(',',$v['image']);
            if($v['member_list_id'] != session('member_list_id') && $v['is_del'] == 1){
                unset($evaluation[$k]);
            }
        }
        $data['list'] = $evaluation;
        $this->make_json_result(1,$data);
    }

    // 餐品评价加载更多
    public function eitemListG(){
        $p = I('k',0,'intval');
        $dishes_id = I('dishes_id');
        $num = 10;//每页记录数
        $limitpage = ($p)*$num;//每次查
        $where['b.dishes_id'] = $dishes_id;
        //$where['a.is_del'] = 2;
        $evaluation = M('comment as a')->join("LEFT JOIN sm_orders as b on a.order_id = b.order_id")
            ->join("LEFT JOIN sm_member_list as c on a.member_list_id = c.member_list_id")->where($where)->limit($limitpage,$num)->order('a.addtime DESC')
            ->field('a.member_list_id,a.is_del,c.member_list_headpic,c.member_list_nickname,a.dish_score,a.service_score,a.addtime,a.image,a.content,a.order_id,b.dishes_name as names')
            ->select();
        foreach ($evaluation as $k => $v){
            //$score = $v['dish_score']+$v['service_score'];
            $score = $v['dish_score'];
            $evaluation[$k]['addtime'] = date("Y-m-d H:i",$v['addtime']);
            $evaluation[$k]['score'] = ceil($score);
            $evaluation[$k]['endscore'] = 5-ceil($score);
            $evaluation[$k]['images'] = explode(',',$v['image']);
            if($v['member_list_id'] != session('member_list_id') && $v['is_del'] == 1){
                unset($evaluation[$k]);
            }
        }
        $data['list'] = $evaluation;
        $this->make_json_result(1,$data);
    }

    //判断菜品是否已售罄
    public function passGoods()
    {
        $dishes_id = I('dishes_id');
        $shopData = M('dishes')->join("AS a LEFT JOIN __MERCHANT__ as c on a.ma_id = c.ma_id")->where("a.dishes_id='$dishes_id'")->field("a.num,c.start_time,c.end_time")->find();
        $startTime = date("Y-m-d",time())." ".date("H:i",$shopData['start_time']);
        $endTime = date("Y-m-d",time())." ".date("H:i",$shopData['end_time']);
        if(strtotime($startTime)>time() || strtotime($endTime)<time()){
            $this->error('餐厅已打烊！餐厅营业时间为：'.date("H:i",$shopData['start_time']).'～'.date("H:i",$shopData['end_time']),1,2);
        }
        $pass = M('dishes')->where("dishes_id='$dishes_id'")->getField("num");
        if($pass == 0){
            $this->error('该菜品已售罄！',1,2);
        }else{
            $this->success('正在跳转！',U('Home/Package/settlement',array('dishes_id'=>$dishes_id)),1);
        }
    }

    //测试
    public function test()
    {
        $this->display();
        //自定义回复

    }
}